<?php
/**
 * Plugin Name: WPUI Frappe Plugin Starter
 * Description: Demonstrates @lubusin/wp-frappe-data-store in a full-page WordPress admin screen using @wordpress/boot and @wordpress/build.
 * Version: 0.1.0
 * Requires at least: 7.0
 * Requires PHP: 7.4
 * Author: LUBUS
 * Author URI: https://lubus.in
 * License: MIT
 * License URI: https://opensource.org/license/mit
 * Text Domain: wpui-frappe-plugin-starter
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'WPUI_FRAPPE_VERSION', '0.1.0' );
define( 'WPUI_FRAPPE_FILE', __FILE__ );

$wpui_frappe_build = plugin_dir_path( __FILE__ ) . 'build/build.php';
if ( file_exists( $wpui_frappe_build ) ) {
	require_once $wpui_frappe_build;
} else {
	add_action(
		'admin_notices',
		static function () {
			if ( current_user_can( 'activate_plugins' ) ) {
				echo '<div class="notice notice-error"><p>' . esc_html__( 'WPUI Frappe Plugin Starter is missing its production build. Run npm run build before packaging the plugin.', 'wpui-frappe-plugin-starter' ) . '</p></div>';
			}
		}
	);
}

// Register REST API proxy for Frappe CRM requests.
require_once plugin_dir_path( __FILE__ ) . 'includes/class-rest-proxy.php';

add_action( 'rest_api_init', static function () {
	$proxy = new WPUI_Frappe_REST_Proxy();
	$proxy->register_routes();
} );

// Register application menu items server-side for the frappe-data-store page.
add_action( 'frappe-data-store_init', static function () {
	// Ensure wpApiSettings (REST root URL and nonce) are initialized for wp.apiFetch since early render bypasses admin_enqueue_scripts.
	if ( wp_script_is( 'wp-api-fetch', 'registered' ) || wp_script_is( 'wp-api-fetch', 'enqueued' ) ) {
		wp_add_inline_script(
			'wp-api-fetch',
			sprintf(
				'window.wpApiSettings = %s;',
				wp_json_encode(
					array(
						'root'          => esc_url_raw( rest_url() ),
						'nonce'         => wp_create_nonce( 'wp_rest' ),
						'versionString' => 'wp/v2/',
					)
				)
			),
			'before'
		);
	}

	if ( function_exists( 'wp_frappe_data_store_register_frappe_data_store_menu_item' ) ) {
		wp_frappe_data_store_register_frappe_data_store_menu_item( 'leads', __( 'Leads', 'wpui-frappe-plugin-starter' ), '/' );
		wp_frappe_data_store_register_frappe_data_store_menu_item( 'deals', __( 'Deals', 'wpui-frappe-plugin-starter' ), '/deals' );
		wp_frappe_data_store_register_frappe_data_store_menu_item( 'contacts', __( 'Contacts', 'wpui-frappe-plugin-starter' ), '/contacts' );
		wp_frappe_data_store_register_frappe_data_store_menu_item( 'organizations', __( 'Organizations', 'wpui-frappe-plugin-starter' ), '/organizations' );
		wp_frappe_data_store_register_frappe_data_store_menu_item( 'notes', __( 'Notes', 'wpui-frappe-plugin-starter' ), '/notes' );
		wp_frappe_data_store_register_frappe_data_store_menu_item( 'tasks', __( 'Tasks', 'wpui-frappe-plugin-starter' ), '/tasks' );
		wp_frappe_data_store_register_frappe_data_store_menu_item( 'settings', __( 'Connection', 'wpui-frappe-plugin-starter' ), '/settings' );
	}
} );

// Register the full-page admin menu item.
add_action( 'admin_menu', static function () {
	// The callback is generated by @wordpress/build based on wpPlugin.name ('wp_frappe_data_store')
	// and the page id ('frappe-data-store').
	if ( function_exists( 'wp_frappe_data_store_frappe_data_store_render_page' ) ) {
		add_menu_page(
			__( 'Frappe CRM', 'wpui-frappe-plugin-starter' ),
			__( 'Frappe CRM', 'wpui-frappe-plugin-starter' ),
			'manage_options',
			'frappe-data-store',
			'wp_frappe_data_store_frappe_data_store_render_page',
			'dashicons-database',
			30
		);
	}
} );
