<?php
/**
 * Plugin Name: WPUI Frappe Plugin Starter
 * Description: Demonstrates @lubusin/wp-frappe-data-store in a full-page WordPress admin screen using @wordpress/boot and @wordpress/build.
 * Version: 0.1.0
 * Author: LUBUS
 * Author URI: https://lubus.in
 * License: GPL-2.0-or-later
 * Text Domain: wpui-frappe-plugin-starter
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Load generated build files from @wordpress/build.
if ( file_exists( plugin_dir_path( __FILE__ ) . 'build/build.php' ) ) {
	require_once plugin_dir_path( __FILE__ ) . 'build/build.php';
}

// Register REST API proxy for Frappe CRM requests.
require_once plugin_dir_path( __FILE__ ) . 'includes/class-rest-proxy.php';

add_action( 'rest_api_init', function () {
	$proxy = new WP_Frappe_Data_Store_REST_Proxy();
	$proxy->register_routes();
} );

// Register application menu items server-side for the frappe-data-store page.
add_action( 'frappe-data-store_init', function () {
	// Ensure wpApiSettings (REST root URL and nonce) are initialized for wp.apiFetch since early render bypasses admin_enqueue_scripts.
	if ( wp_script_is( 'wp-api-fetch', 'registered' ) || wp_script_is( 'wp-api-fetch', 'enqueued' ) ) {
		wp_add_inline_script(
			'wp-api-fetch',
			sprintf(
				'window.wpApiSettings = %s;',
				wp_json_encode(
					array(
						'root'          => esc_url_raw( rest_url() ),
						'nonce'         => wp_create_nonce( 'wp_rest' ),
						'versionString' => 'wp/v2/',
					)
				)
			),
			'before'
		);
	}

	if ( function_exists( 'wp_frappe_data_store_register_frappe_data_store_menu_item' ) ) {
		wp_frappe_data_store_register_frappe_data_store_menu_item( 'leads', __( 'Leads', 'wp-frappe-data-store-sample' ), '/' );
		wp_frappe_data_store_register_frappe_data_store_menu_item( 'deals', __( 'Deals', 'wp-frappe-data-store-sample' ), '/deals' );
		wp_frappe_data_store_register_frappe_data_store_menu_item( 'contacts', __( 'Contacts', 'wp-frappe-data-store-sample' ), '/contacts' );
		wp_frappe_data_store_register_frappe_data_store_menu_item( 'organizations', __( 'Organizations', 'wp-frappe-data-store-sample' ), '/organizations' );
		wp_frappe_data_store_register_frappe_data_store_menu_item( 'notes', __( 'Notes', 'wp-frappe-data-store-sample' ), '/notes' );
		wp_frappe_data_store_register_frappe_data_store_menu_item( 'tasks', __( 'Tasks', 'wp-frappe-data-store-sample' ), '/tasks' );
		wp_frappe_data_store_register_frappe_data_store_menu_item( 'settings', __( 'Connection', 'wp-frappe-data-store-sample' ), '/settings' );
	}
} );

// Register the full-page admin menu item.
add_action( 'admin_menu', function () {
	// The callback is generated by @wordpress/build based on wpPlugin.name ('wp_frappe_data_store')
	// and the page id ('frappe-data-store').
	if ( function_exists( 'wp_frappe_data_store_frappe_data_store_render_page' ) ) {
		add_menu_page(
			__( 'Frappe CRM', 'wp-frappe-data-store-sample' ),
			__( 'Frappe CRM', 'wp-frappe-data-store-sample' ),
			'manage_options',
			'frappe-data-store',
			'wp_frappe_data_store_frappe_data_store_render_page',
			'dashicons-database',
			30
		);
	}
} );
