/**
 * Post-build script for standalone @wordpress/build plugins.
 *
 * In WordPress Core (Gutenberg), @wordpress/boot is built locally into
 * build/modules/boot/index.min.asset.php. When @wordpress/build generates
 * page.php for a third-party plugin, it hardcodes a check for that file before
 * enqueuing application prerequisites and boot initialization scripts.
 *
 * Since standalone plugins import @wordpress/boot from WordPress Core rather
 * than building it locally, this script acts as an automated build bridge:
 * 1. Scans all auto-generated .asset.php files across build/modules,
 *    build/routes, and build/scripts.
 * 2. Extracts and dynamically aggregates all WordPress script dependencies
 *    discovered in our built bundles.
 * 3. Merges them with core administrative prerequisites required by @wordpress/boot.
 * 4. Computes a dynamic SHA-1 version hash based on the build artifacts.
 * 5. Emits build/modules/boot/index.min.asset.php so page.php boots cleanly.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';

const __dirname = path.dirname( fileURLToPath( import.meta.url ) );
const buildDir = path.resolve( __dirname, '../build' );
const bootDir = path.join( buildDir, 'modules/boot' );
const assetFile = path.join( bootDir, 'index.min.asset.php' );

// Recursively find all .asset.php files generated by wp-build
function findAssetFiles( dir, fileList = [] ) {
	if ( ! fs.existsSync( dir ) ) {
		return fileList;
	}
	const entries = fs.readdirSync( dir, { withFileTypes: true } );
	for ( const entry of entries ) {
		const fullPath = path.join( dir, entry.name );
		if ( entry.isDirectory() && entry.name !== 'boot' ) {
			findAssetFiles( fullPath, fileList );
		} else if ( entry.isFile() && entry.name.endsWith( '.asset.php' ) ) {
			fileList.push( fullPath );
		}
	}
	return fileList;
}

const assetFiles = findAssetFiles( buildDir );
const discoveredDependencies = new Set();
const hashBuilder = crypto.createHash( 'sha1' );

for ( const file of assetFiles ) {
	const content = fs.readFileSync( file, 'utf8' );
	hashBuilder.update( content );

	// Extract dependencies array from generated PHP asset files
	const match = content.match( /['"]dependencies['"]\s*=>\s*array\(\s*([^)]*)\s*\)/ );
	if ( match && match[ 1 ] ) {
		const deps = match[ 1 ]
			.split( ',' )
			.map( ( s ) => s.trim().replace( /^['"]|['"]$/g, '' ) )
			.filter( Boolean );
		for ( const dep of deps ) {
			discoveredDependencies.add( dep );
		}
	}
}

// Ensure administrative prerequisites required by @wordpress/boot are always enqueued
const bootCorePrerequisites = [
	'wp-a11y',
	'wp-api-fetch',
	'wp-commands',
	'wp-core-data',
	'wp-dom-ready',
	'wp-editor',
	'wp-html-entities',
	'wp-keyboard-shortcuts',
	'wp-notices',
	'wp-plugins',
	'wp-preferences',
	'wp-url',
];
for ( const coreDep of bootCorePrerequisites ) {
	discoveredDependencies.add( coreDep );
}

const sortedDependencies = Array.from( discoveredDependencies ).sort();
const versionHash = hashBuilder.digest( 'hex' ).slice( 0, 20 );

const phpContent = `<?php
/**
 * Boot module asset prerequisites for standalone plugin execution.
 * Auto-generated by scripts/postbuild.mjs by scanning build artifacts.
 */
return array(
	'dependencies' => array(
${ sortedDependencies.map( ( dep ) => `\t\t'${ dep }',` ).join( '\n' ) }
	),
	'version' => '${ versionHash }',
);
`;

fs.mkdirSync( bootDir, { recursive: true } );
fs.writeFileSync( assetFile, phpContent, 'utf8' );
console.log(
	`   ✔ Generated build/modules/boot/index.min.asset.php (aggregated ${ sortedDependencies.length } dependencies, version ${ versionHash })`
);
